# Generated by Django 4.2.3 on 2023-08-15 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='thana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.thana'),
        ),
    ]
