# Generated by Django 4.2.3 on 2023-08-15 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_hospital_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationhistory',
            old_name='date',
            new_name='donation_date',
        ),
    ]
