# Generated by Django 3.2.12 on 2023-08-16 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_date_donationhistory_donation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hospital',
        ),
    ]
