# Generated by Django 3.2.12 on 2023-08-16 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_post_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.hospital'),
        ),
    ]
