# Generated by Django 3.2.12 on 2023-08-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_post_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
